INSERT INTO departments (id, department_name) 
VALUES ("Crew"),
       ("Cast"),
       ("Martial Arts"),
       ("Investors");

INSERT INTO roles (title, salary, department_id)
VALUES ("Actor", 250, 2),
       ("Assistant Cameraman", 250, 1),
       ("Assistant Director", 250, 1),
       ("Backer", 500, 4),
       ("Cinematographer", 500, 1),
       ("Director", 3000, 1),
       ("Editor", 2000, 1),
       ("Fight Choreographer", 750, 3),
       ("Gaffer", 700, 1),
       ("Grip", 600, 1),
       ("Lightweight Karate Champion", 500, 3),
       ("Make-up", 600, 1),
       ("Martial Arts Assistant Director", 300, 3),
       ("Master Samurai Swordsman", 400, 3),
       ("Music Arranger", 500, 1),
       ("Music Consultant", 250, 1),
       ("Negative Editor", 600, 1),
       ("Producer", 500, 1),
       ("Production Assistant", 250, 1),
       ("Production Manager", 200, 1),
       ("Set Decorator", 100, 1),
       ("Sound Editor", 450, 1),
       ("Sound Engineer", 600, 1),
       ("Special Effects", 500, 1),
       ("Writer", 700, 1);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES ("Malaika", "Ahraam", 1, 29),  
       ("Al", "Banks", 1, 29),    
       ("Vince", "Barbi", 1, 29), 
       ("Joseph", "Bihari", 4, NULL),
       ("Julius", "Bihari", 4, NULL),
       ("Lester", "Bihari", 4, NULL),
       ("Ted", "Brinson", 16, 15),
       ("Marie", "Carter", 1, 29),
       ("Junior", "Cranberry", 1, 29),
       ("Norval", "Crutcher", 22, NULL),
       ("Gene", "Davis", 8, 35),
       ("Von", "Dutch", 24, 40),
       ("Warde", "Egan", 1, 29),
       ("Mother", "Fear", 1, 29),
       ("Bobbie", "George", 2, 40),
       ("James", "Gough", 13, 35),
       ("Timothy", "Grace", 10, 40),
       ("John Ashley", "Hamilton", 3, 40),
       ("Josephine", "Harris", 1, 29),
       ("Michael", "Hereford", 2, 40),
       ("Howard", "Jackson", 11, 35),
       ("Claudia", "Jackson", 20, 29),
       ("Jerry", "Jones", 25, 32),
       ("John", "Kirkland", 9, 40),
       ("Jack", "LaMantain", 17, 28),
       ("Jean", "Lewis", 19, 29),
       ("Princess", "Lilio", 1, 29),
       ("Rex", "Lipton", 7, 32),
       ("D’Urville", "Martin", 6, 32),
       ("Hugh", "McDonald", 13, 35),
       ("Carmella", "Di Milo", 1, 29),
       ("Rudy Ray", "Moore", 18, 5),
       ("Eric", "Nero", 13, 35),
       ("Randy", "Ornelas", 10, 40),
       ("Curtis", "Pulliam", 13, 29),
       ("Hy", "Pyke", 1, 29),
       ("Lady", "Reed", 1, 29),
       ("Marvin", "Reese", 21, 29),
       ("George", "Selin", 10, 40),
       ("Nicholas", "Josef von Sternberg", 5, 29),
       ("Bruce", "Stevens", 1, 29),
       ("John", "Wagner", 10, 40),
       ("Harry", "Wollman", 24, 40),
       ("Arthur", "Wright", 16, 32),
       ("Carol", "Yasunaga", 23, 40);
